### ISSUE TITLE
implementar correctamente protocolos multiplayer

### ISSUE THREAD

**Issue by fernando-lahoz** [UNIZAR-30226-2023-01/chess-mobile#25]

**Comment by FranciscoJavierPizarro** [comment]
funciona con la versión antigua del protocolo, falta actualizar a la nueva versión y actualizar el backend

**Comment by FranciscoJavierPizarro** [comment]
nueva versión del protocolo funcionando contra la IA, el multiplayer no funciona porque no tenemos todavía los token por el fallo de las comunicaciones con la REST api
